// This file is auto-generated by @hey-api/openapi-ts

export const $AnonymizationRequest = {
    properties: {
        original_messages: {
            items: {
                '$ref': '#/components/schemas/Message'
            },
            type: 'array',
            title: 'Original Messages'
        },
        deanonymization_mapping: {
            additionalProperties: {
                additionalProperties: {
                    type: 'string'
                },
                type: 'object'
            },
            type: 'object',
            title: 'Deanonymization Mapping'
        },
        allow_list: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Allow List'
        },
        entities: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Entities'
        }
    },
    type: 'object',
    required: ['original_messages', 'deanonymization_mapping', 'allow_list', 'entities'],
    title: 'AnonymizationRequest'
} as const;

export const $AnonymizationResponse = {
    properties: {
        anonymized_messages: {
            items: {
                '$ref': '#/components/schemas/Message'
            },
            type: 'array',
            title: 'Anonymized Messages'
        },
        updated_deanonymization_mapping: {
            additionalProperties: {
                additionalProperties: {
                    type: 'string'
                },
                type: 'object'
            },
            type: 'object',
            title: 'Updated Deanonymization Mapping'
        }
    },
    type: 'object',
    required: ['anonymized_messages', 'updated_deanonymization_mapping'],
    title: 'AnonymizationResponse'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $Message = {
    properties: {
        role: {
            type: 'string',
            title: 'Role'
        },
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['role', 'content'],
    title: 'Message'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;