// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise'
import { OpenAPI } from './core/OpenAPI'
import { request as __request } from './core/request'
import type {
  PostChatbotMessageMessagesAnonymizePostData,
  PostChatbotMessageMessagesAnonymizePostResponse
} from './types.gen'

/**
 * Post Chatbot Message
 * @param data The data for the request.
 * @param data.requestBody
 * @returns AnonymizationResponse Successful Response
 * @throws ApiError
 */
export const postChatbotMessageMessagesAnonymizePost = (
  data: PostChatbotMessageMessagesAnonymizePostData
): CancelablePromise<PostChatbotMessageMessagesAnonymizePostResponse> => {
  return __request(OpenAPI, {
    method: 'POST',
    url: '/messages/anonymize',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
      422: 'Validation Error'
    }
  })
}
