// This file is auto-generated by @hey-api/openapi-ts

export type AnonymizationRequest = {
  original_messages: Array<Message>
  deanonymization_mapping: {
    [key: string]: {
      [key: string]: string
    }
  }
  allow_list: Array<string>
  entities: Array<string>
}

export type AnonymizationResponse = {
  anonymized_messages: Array<Message>
  updated_deanonymization_mapping: {
    [key: string]: {
      [key: string]: string
    }
  }
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type Message = {
  role: string
  content: string
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type PostChatbotMessageMessagesAnonymizePostData = {
  requestBody: AnonymizationRequest
}

export type PostChatbotMessageMessagesAnonymizePostResponse =
  AnonymizationResponse

export type $OpenApiTs = {
  '/messages/anonymize': {
    post: {
      req: PostChatbotMessageMessagesAnonymizePostData
      res: {
        /**
         * Successful Response
         */
        200: AnonymizationResponse
        /**
         * Validation Error
         */
        422: HTTPValidationError
      }
    }
  }
}
